server:
  #这里填你的服务器地址以及配置，多个地址请复制粘贴增加，以下为示例
  #- url: "example.com" 服务器地址
  #  port: 25565 服务器端口，默认为25565
  #  version: "1.xx.x" 服务器版本，格式为1.xx.x/xx.x/1.xx
  - url: ""
    port: 25565
    version: "1.xx.x"

connect:
  #这里填你的与外部的连接设置，以下为示例
  #- timeout: 10 连接超时时间，单位为秒，默认为10秒
  #  retry: 3 连接重试次数，默认为3次
  #  host: "localhost" 连接的主机地址，默认为localhost
  #  port: xxxxx 连接的端口
  timeout: 10
  retry: 3
  host: "localhost"
  port: xxxxx
  